engines:
  git-legal:
    enabled: true
  eslint:
    enabled: true
    channel: "eslint-4"
  fixme:
    enabled: true
  csslint:
    enabled: true
  markdownlint:
    enabled: true
  nodesecurity:
    enabled: true
  stylelint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript:
ratings:
  paths:
  - "lib/*.js"
  - "*.js"

exclude_paths:
- "test/*"
