sudo: required

language: node

services:
  - docker

before_install:
  - docker build -t justintime4tea/alexa-skill-template . -f Dockerfile

script:
  - docker run -e "CODECOV_TOKEN=$CODECOV_TOKEN" -e "CODACY_PROJECT_TOKEN=$CODACY_PROJECT_TOKEN" -e "CODECLIMATE_REPO_TOKEN=$CODECLIMATE_REPO_TOKEN" justintime4tea/alexa-skill-template npm run report-coverage
